server:
  port: 8081

spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://192.168.0.102:3306/employee_db  # ✅ Change from localhost to your MySQL IP
    username: sangharsh
    password: Sangharsh724
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: https://employee-registry-3yo1.onrender.com/eureka  # ✅ Use public Eureka URL
    register-with-eureka: true
    fetch-registry: true

info:
  app:
    name: employee-service
    version: 1.0.0
